# Site settings
title: Steve Grossi at Work
email: hello@stevegrossi.com
description: Thoughts on software craftsmanship.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://work.stevegrossi.com"
permalink: pretty
paginate: 10
paginate_path: "/page/:num/"
twitter:
  username: stevegrossi
github:
  username:  stevegrossi
author:
  picture: /img/stevegrossi.jpg
  twitter: stevegrossi

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from _site
exclude:
  - CNAME
  - README.markdown
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  talks:
    output: true
    permalink: /talks/:title

# Default post options
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
